### ISSUE TITLE
Entity.assign no longer produces ComponentAdded event for NexusEventDelegate

### ISSUE THREAD

**Issue by igorkravchenko** [fireblade-engine/ecs#36]
Steps to reproduce:
```
import FirebladeECS

let nexus = Nexus()

class EventDelegate: NexusEventDelegate {
    func nexusEvent(_ event: NexusEvent) {
        if event is ComponentAdded {
            print("component added")
        }
    }
    
    func nexusNonFatalError(_ message: String) {}
}

let delegate = EventDelegate()
nexus.delegate = delegate

class Comp: Component {}
class Comp2: Component {}


nexus.createEntity().assign(Comp(), Comp2())
```

In 0.17.2 the ComponentAdded event is triggered.

**Comment by ctreffs** [comment]
Affected version: 0.17.3

**Comment by ctreffs** [comment]
Hi @igorkravchenko ,

thanks for reporting this. 
It was in fact a bug, which will be fixed with PR #37.
I will create a patch release `0.17.4` for that in the future, but you will be able to pull the bugfix from `master` as soon as the PR is merged.

That you again and have a great week 👋

**Comment by ctreffs** [comment]
PR #37 is now merged. Please give me some feedback if this solved your issue, so that the issue can be closed. Thank you 🙏

**Comment by igorkravchenko** [comment]
Yeah, recent PR solves the issue for me. Thank you!
