### ISSUE TITLE
DocC Documentation

### ISSUE THREAD

**Issue by ctreffs** [fireblade-engine/ecs#76]
### Feature request

We currently do have a CI workflow [`documentation.yml`](https://github.com/fireblade-engine/ecs/blob/master/.github/workflows/documentation.yml) in place (that's broken). It uses an old and outdated way to generate documentation that is published to this repositories [Wiki pages](https://github.com/fireblade-engine/ecs/wiki).
That's neither nice nor good to maintain.
[DocC](https://www.swift.org/documentation/docc/) is the de-facto standard for Swift project nowadays.
We should migrate to DocC to generate documentation for this project.
A good starting point is: https://swiftlang.github.io/swift-docc-plugin/documentation/swiftdoccplugin

### Describe the solution you'd like

- [ ] Use DocC to generate documentation.
- [ ] Show documentation at [SwiftPackageIndex](https://swiftpackageindex.com/fireblade-engine/ecs) ([SPI-Manifest Documentation](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.7.0/documentation/spimanifest))
- [ ] Add rules to [Makefile](https://github.com/fireblade-engine/ecs/blob/master/Makefile) to [generate](https://swiftlang.github.io/swift-docc-plugin/documentation/swiftdoccplugin/generating-documentation-for-a-specific-target/) and [preview](https://swiftlang.github.io/swift-docc-plugin/documentation/swiftdoccplugin/previewing-documentation/) documentation
- [ ] Update [Documentation CI workflow](https://github.com/fireblade-engine/ecs/blob/master/.github/workflows/documentation.yml) to [publish documentation to GitHub pages/wiki](https://swiftlang.github.io/swift-docc-plugin/documentation/swiftdoccplugin/publishing-to-github-pages/) or remove and update README if superseded by SPI
- [ ] Extend documentation content with module pages
- [ ] Bonus: [Add interactive tutorial](https://www.swift.org/documentation/docc/tutorial)

### Describe alternatives you've considered

Manual generation steps are tedious to maintain and don't offer as many proven features as DocC does.

**Comment by heckj** [comment]
I'd be more than happy to set you up with this. Worth noting that once enabled, with an `.spi.yml` file, you'll get hosted documentation through the Swift Package Index if you'd like to take advantage of that. Is there a place you'd explicitly like to host docs? (e.g. GitHub pages for this repository?)

**Comment by ctreffs** [comment]
Documentation on Swift Package Index would be great. Other than that I don't really have a strong opinion where documentation is hosted, as long as it's easily available to users. If we'd only provide documentation on SPI that would be fine by me, but are there drawbacks to how current documentation would be (e.g. only generated when there is a new tag available)?
The generation part of DocC is easy enough, adjusting CI as well, but regarding hosting and publishing I'm currently a little lost. So if you want I could tackle the first bit (Plugin & CI integration) and you'd extend it with hosting & publishing? Sounds like a plan @heckj?

**Comment by heckj** [comment]
I'm away from my laptop this week, but once back I'll get a quick PR set up to host the docs.
